version: '3.8'

services:
  backend:
    build: ./Govt-Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Govt-Backend:/app
      - backend_data:/app/data
      - backend_uploads:/app/uploads
    environment:
      - NODE_ENV=development
    command: npm run dev

  frontend:
    build: ./Govt-Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Govt-Frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    command: npm start

volumes:
  backend_data:
  backend_uploads: